[build]
  command   = "pnpm build"
  publish   = "out"

[[redirects]]
  from = "https://www.pablo.dev/*"
  to = "https://pablo.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pablo-dev.netlify.app/*"
  to = "https://pablo.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
[headers.values]
    Content-Security-Policy = "default-src 'self' www.notion.so; connect-src 'self'; font-src 'self'; img-src 'self' data: www.notion.so; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "accelerometer=(),  camera=(), geolocation=(), gyroscope=(), magnetometer=(),  microphone=(), midi=(), payment=(), speaker=(), usb=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
