[build]
  command   = "yarn build-netlify"
  functions = "out_functions"
  publish   = "out_publish"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' data: haddock.pablo.dev; report-uri https://pablodev.report-uri.com/r/d/csp/enforce"
