[build]
  command   = "yarn build-netlify"
  functions = "out_functions"
  publish   = "out_publish"

[[redirects]]
  from = "https://www.pablo.dev/*"
  to = "https://pablo.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pablo-dev.netlify.app/*"
  to = " https://pablo.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' data: haddock.pablo.dev; report-uri https://pablodev.report-uri.com/r/d/csp/enforce; report-to https://pablodev.report-uri.com/r/d/csp/enforce"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://pablodev.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    NEL = "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
    Expect-CT = "max-age=0, report-uri=\"https://pablodev.report-uri.com/r/d/ct/reportOnly\""
    Referrer-Policy = "no-referrer"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; speaker 'none'; usb 'none'"
    Permissions-Policy = "accelerometer=(),  camera=(), geolocation=(), gyroscope=(), magnetometer=(),  microphone=(), midi=(), payment=(), speaker=(), usb=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

