[build]
  command   = "yarn build-netlify"
  functions = "out_functions"
  publish   = "out_publish"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' data: haddock.pablo.dev; report-uri https://pablodev.report-uri.com/r/d/csp/enforce; report-to https://pablodev.report-uri.com/r/d/csp/enforce"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://pablodev.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    NEL = "{\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "geolocation 'none'; midi 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none';"
